### ISSUE TITLE
Quick demo! 2 months of building

### ISSUE THREAD

**Issue by johnlafleur** [airbytehq/write-for-airbyte#1]
A quick video demo of what we have built in the last 2 months. 
This would be the 1st video of a series of videos that we could publish every month with the new features/progress of the latest month. This could be a new approach to changelogs that we could publish on external publication platforms, such as dev.to.

**Comment by avaidyanatha** [comment]
Would be harder to do from an outside perspective, this should be done in collaboration with the Core team.
