### ISSUE TITLE
[TOPIC] Build vs. Buy isn't a question anymore: Airbyte makes both easy

### ISSUE THREAD

**Issue by johnlafleur** [airbytehq/write-for-airbyte#26]
Some inspiration: https://fivetran.com/blog/build-vs-buy-by-the-numbers

**Comment by johnlafleur** [comment]
We actually wrote this: https://airbyte.io/blog/how-open-source-can-disrupt-build-vs-buy-considerations
I think we can close this issue, but let you assess.

**Comment by avaidyanatha** [comment]
@johnlafleur Looks like you had my idea way earlier ahaha, good stuff. Closing.
