### ISSUE TITLE
[TOPIC] Save all public Slack messages

### ISSUE THREAD

**Issue by johnlafleur** [airbytehq/write-for-airbyte#28]
- We need to choose in which DB or warehouse to store the messages. 
- We could use Algolia to search for messages, they offer their service for free for open-source projects: https://www.algolia.com/for-open-source/

**Comment by michel-tricot** [comment]
We could also use meilisearch what do you think @qdequele ?

**Comment by qdequele** [comment]
Absolutely! It's a perfect fit.

**Comment by avaidyanatha** [comment]
This is done. https://docs.airbyte.io/examples/slack-history
