### ISSUE TITLE
[TOPIC] Building a Slack activity dashboard using Airbyte and Preset

### ISSUE THREAD

**Issue by johnlafleur** [airbytehq/write-for-airbyte#31]
Inspiration:
- https://preset.io/blog/2020-09-22-slack-dashboard/
- https://preset.io/blog/2020-10-02-slack-dashboard-part-2/
- https://preset.io/blog/2020-11-04-slack-dashboard-part-3/

Metrics that we would like to see in the dashboard:
- evolution of the # members
- evolution of the # weekly active members (WAU) (meaning they posted a message or read at least one channel or direct message) and monthly active members (MAU)
- evolution of the # messages with distinction between team and community members, so 2 lines. 
- time to 1st reply in thread for non-team members (50%, 90% percentile) - meaning for any message made by non-team members for which a thread is created, what is the time to first reply in the thread. So we don't consider messages without threads. 
- # messages posted per channel for past month and in total
- evolution of the # members per timezone and of weekly active members

**Comment by ChristopheDuong** [comment]
This is very close to #29  (too close?)

The two are probably going to be very similar on the back-end stack and you just need to switch the latest dataviz solutions between the two

**Comment by johnlafleur** [comment]
We could use a different visualization tools between both, as it could enable us to do co-marketing opportunities with both of them, and if any of our users use one of both tools, they will have a tutorial. 

Here is what the dashboard could look like: https://docs.google.com/presentation/d/1JRawv_gbyM7IVnVJLQ2-e1B4fMbDuxdBqeJJXli2FDs/edit?usp=sharing

**Comment by DominusKelvin** [comment]
I would start work on this @johnlafleur

**Comment by avaidyanatha** [comment]
This is completed. https://docs.airbyte.io/examples/build-a-slack-activity-dashboard
