### ISSUE TITLE
[TOPIC] How to uncover the time spent by your team in Zoom calls (using Airbyte and Tableau)

### ISSUE THREAD

**Issue by johnlafleur** [airbytehq/write-for-airbyte#39]
- Set up data replication from Zoom to a database supported by Tableau: https://docs.airbyte.io/integrations/sources/zoom
- Plug Tableau
- Product the following charts: 
    - Meetings:
        - Evolution of the # meetings per week in the team
        - Evolution of the # hours per week in meeting in the team
        - Evolution of the # external participants for all meeting in the team per week
        - Listing of team members with the number of meetings per week and number of hours spent in meeting, ranked
    - Webinars:
        - Evolution of the # webinar per week in the team
        - Evolution of the # hours per week in webinars in the team
        - Evolution of the # participants for all webinars in the team per week
        - Listing of team members with the number of webinars per week and number of hours spent in meeting, ranked

**Comment by DominusKelvin** [comment]
And this :)
